version: '3.4'

services:
  sm.mvc.web:
    image: monitoring/api
    container_name: monitoring_api
    build:
      context: .
      dockerfile: SM.MVC.Web/Dockerfile
    ports:
      - 15422:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DatabaseServer: "SqlDocker"
      DatabasePort: "14331"
      DatabaseUser: "SA"
      DatabasePassword: "Omid3883"
      DatabaseName: "SoftwareMonitorDB"
    depends_on:
     - SqlDocker
  SqlDocker:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: DockerDB
    environment:
      SA_PASSWORD: "Omid3883"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"